# Generated by Django 3.2.5 on 2021-07-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь авторизован'),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='Корзина используется'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объём SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.CharField(max_length=255, verbose_name='Размер экрана'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_type',
            field=models.CharField(max_length=255, verbose_name='Технология экрана'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие слота для SD карты'),
        ),
    ]
