# Generated by Django 3.2.6 on 2021-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210814_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/images', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/images', verbose_name='Изображение товара'),
        ),
    ]
